INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Top Valeria' ,'450','Negro','Top negro con mangas acampanadas','https://ibb.co/1spmPBJ','https://ibb.co/1spmPBJ','https://ibb.co/1spmPBJ','https://ibb.co/1spmPBJ','Ellas','MXN','Blusa con mangas campana transparentes y cintas en cintura.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Falda Alicia' ,'450','Negro','Falda negra corta','https://ibb.co/3Nr7d7D','https://ibb.co/3Nr7d7D','https://ibb.co/3Nr7d7D','https://ibb.co/3Nr7d7D','Ellas','MXN','Mini falda con abertura en muslos y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Falda Pilar' ,'550','Negro','Falda negra con corte ondulado','https://ibb.co/RzRnXsX','https://ibb.co/RzRnXsX','https://ibb.co/RzRnXsX','https://ibb.co/RzRnXsX','Ellas','MXN','Falda asimétrica con bolsas en costado y olanes.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit' ,'450','Negro','Vinipile','https://ibb.co/3CbG6CK','https://ibb.co/3CbG6CK','https://ibb.co/3CbG6CK','https://ibb.co/3CbG6CK','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación de vinipiel.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Abrigo Moon' ,'700','Negro','Abrigo negro','https://ibb.co/qJcKp0R','https://ibb.co/qJcKp0R','https://ibb.co/qJcKp0R','https://ibb.co/qJcKp0R','Todes','MXN','Abrigo felpa con capucha amplia y bolsas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit Animal Print' ,'450','Rosa','Animal print','https://ibb.co/jgNRZ96','https://ibb.co/jgNRZ96','https://ibb.co/jgNRZ96','https://ibb.co/jgNRZ96','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación animalprint.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit Water' ,'450','Azul','Edicion limitada','https://ibb.co/cTFdQGJ','https://ibb.co/cTFdQGJ','https://ibb.co/cTFdQGJ','https://ibb.co/cTFdQGJ','Ellas','MXN','Jumpsuit tirantes con bolsas, aplicación de dragones.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sudadera Autum' ,'650','Negro','Autum','https://ibb.co/mckRsMn','https://ibb.co/mckRsMn','https://ibb.co/mckRsMn','https://ibb.co/mckRsMn','Todes','MXN','Sudadera con capucha amplia y pasamontañas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Suadera Winter' ,'650','Negro','Winter','https://ibb.co/C6vJjYc','https://ibb.co/C6vJjYc','https://ibb.co/C6vJjYc','https://ibb.co/C6vJjYc','Todes','MXN','Sudadera con capucha y botones, con bolsa enfrente con telas en combinación.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sueter' ,'780','Gris','Sueter gris','https://ibb.co/zNdtcZ1','https://ibb.co/zNdtcZ1','https://ibb.co/zNdtcZ1','https://ibb.co/zNdtcZ1','Todes','MXN','Sudadera asimétrica con detalle de cierre en pecho.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sueter all in black' ,'780','Gris','Sueter gris all in black mode','https://ibb.co/zfFr3kk','https://ibb.co/zfFr3kk','https://ibb.co/zfFr3kk','https://ibb.co/zfFr3kk','Todes','MXN','Sudadera asimétrica con detalle de cierre en pecho y bordado “All in Black Mood”.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Top Katherine' ,'250','Negro','Top negro con mangas trasparentes','https://ibb.co/j3B369K','https://ibb.co/j3B369K','https://ibb.co/j3B369K','https://ibb.co/j3B369K','Ellas','MXN','Crop top con mangas transparentes.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Pants Rex' ,'650','Negro','Pants negro','https://ibb.co/ss36yY6','https://ibb.co/ss36yY6','https://ibb.co/ss36yY6','https://ibb.co/ss36yY6','Todes','MXN','Jogger con aplicación en costado, elástico y jareta.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jogger Rex' ,'650','Negro','Jogger negro','https://ibb.co/W2HdYgX','https://ibb.co/W2HdYgX','https://ibb.co/W2HdYgX','https://ibb.co/W2HdYgX','Todes','MXN','Jogger con aplicación en cintura enfrente y atrás, con elástico y jareta.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Air Rosa' ,'250','Rosa','Blusa rosa con espalda en A','https://ibb.co/sjMbBRQ','https://ibb.co/sjMbBRQ','https://ibb.co/sjMbBRQ','https://ibb.co/sjMbBRQ','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Air Negro' ,'250','Negro','Blusa negra con espalda en A','https://ibb.co/SKYndqX','https://ibb.co/SKYndqX','https://ibb.co/SKYndqX','https://ibb.co/SKYndqX','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Camisa Autum' ,'650','Negro','Camisa formal','https://ibb.co/4dSC0Rv','https://ibb.co/4dSC0Rv','https://ibb.co/4dSC0Rv','https://ibb.co/4dSC0Rv','Todes','MXN','Camisa formal con apicacion en los costados.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Camisa Moon' ,'650','Negro','Camisa estilo oriental','https://ibb.co/F7M3rYN','https://ibb.co/F7M3rYN','https://ibb.co/F7M3rYN','https://ibb.co/F7M3rYN','Todes','MXN','Camisa negra estilo oriental con detalle en botones.');


INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Patricio','Estrella','patricio@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Bob','Esponja','esponja@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'BobEsp31', 'Cangreburger');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Calamardo','Tentaculos','calamardo@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
