INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Top Valeria' ,'450','Negro','Top negro con mangas acampanadas','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','Ellas','MXN','Blusa con mangas campana transparentes y cintas en cintura.','Blusa');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Falda Alicia' ,'450','Negro','Falda negra corta','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','Ellas','MXN','Mini falda con abertura en muslos y cintas.','Falda');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Falda Pilar' ,'550','Negro','Falda negra con corte ondulado','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','Ellas','MXN','Falda asimétrica con bolsas en costado y olanes.','Falda');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Jumpsuit Vini' ,'450','Negro','Vinipiel','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación de vinipiel.','Vestido');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Abrigo Moon' ,'700','Negro','Abrigo negro','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','Ellos','MXN','Abrigo felpa con capucha amplia y bolsas.','Chamarra');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Jumpsuit Animal Print' ,'450','Rosa','Animal print','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación animalprint.','Vestido');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Jumpsuit Water' ,'450','Azul','Edicion limitada','https://iili.io/H9ERdkN.jpg','https://iili.io/H9EAmBa.jpg','https://iili.io/H9ERdkN.jpg','https://iili.io/H9EAmBa.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas, aplicación de dragones.','Vestido');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Sudadera Autum' ,'650','Negro','Autum','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','Ellos','MXN','Sudadera con capucha amplia y pasamontañas.','Chamarra');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Suadera Winter' ,'650','Negro','Winter','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','Ellos','MXN','Sudadera con capucha y botones, con bolsa enfrente con telas en combinación.','Chamarra');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Sueter' ,'780','Gris','Sueter gris','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','Ellos','MXN','Sudadera asimétrica con detalle de cierre en pecho.','Chamarra');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Sueter all in black' ,'780','Gris','Sueter gris all in black mode','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','Ellos','MXN','Sudadera asimétrica con detalle de cierre en pecho y bordado “All in Black Mood”.','Chamarra');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Top Katherine' ,'250','Negro','Top negro con mangas trasparentes','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','Ellas','MXN','Crop top con mangas transparentes.','Blusa');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Pants Rex' ,'650','Negro','Pants negro','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','Ellos','MXN','Jogger con aplicación en costado, elástico y jareta.','Pantalon');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Jogger Rex' ,'650','Negro','Jogger negro','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','Ellos','MXN','Jogger con aplicación en cintura enfrente y atrás, con elástico y jareta.','Pantalon');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Air Rosa' ,'250','Rosa','Blusa rosa con espalda en A','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.','Blusa');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Air Negro' ,'250','Negro','Blusa negra con espalda en A','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.','Blusa');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Camisa Autum' ,'650','Negro','Camisa formal','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','Ellos','MXN','Camisa formal con apicacion en los costados.','Blusa');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`imag0`,`imag1`,`imag2`,`target`,`divisa`,`detalle`,`catego`) VALUES ('Camisa Moon' ,'650','Negro','Camisa estilo oriental','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','Ellos','MXN','Camisa negra estilo oriental con detalle en botones.','Blusa');


INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Patricio','Estrella','patricio@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Bob','Esponja','esponja@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'BobEsp31', 'Cangreburger');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Calamardo','Tentaculos','calamardo@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
