INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Top Valeria' ,'450','Negro','Top negro con mangas acampanadas','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','https://iili.io/H9ERCEG.jpg','Ellas','MXN','Blusa con mangas campana transparentes y cintas en cintura.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Falda Alicia' ,'450','Negro','Falda negra corta','https://ibb.co/3Nr7d7D','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','https://iili.io/H9EAthF.png','Ellas','MXN','Mini falda con abertura en muslos y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Falda Pilar' ,'550','Negro','Falda negra con corte ondulado','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','https://iili.io/H9EADLg.jpg','Ellas','MXN','Falda asimétrica con bolsas en costado y olanes.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit Vini' ,'450','Negro','Vinipiel','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','https://iili.io/H9ERJ7p.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación de vinipiel.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Abrigo Moon' ,'700','Negro','Abrigo negro','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','https://iili.io/H9EAi7V.jpg','Todes','MXN','Abrigo felpa con capucha amplia y bolsas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit Animal Print' ,'450','Rosa','Animal print','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','https://iili.io/H9ERH2R.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas aplicación animalprint.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jumpsuit Water' ,'450','Azul','Edicion limitada','https://iili.io/H9ERdkN.jpg','https://iili.io/H9EAmBa.jpg','https://iili.io/H9ERdkN.jpg','https://iili.io/H9EAmBa.jpg','Ellas','MXN','Jumpsuit tirantes con bolsas, aplicación de dragones.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sudadera Autum' ,'650','Negro','Autum','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','https://iili.io/H9ERFIt.png','Todes','MXN','Sudadera con capucha amplia y pasamontañas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Suadera Winter' ,'650','Negro','Winter','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','https://iili.io/H9ERTpS.png','Todes','MXN','Sudadera con capucha y botones, con bolsa enfrente con telas en combinación.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sueter' ,'780','Gris','Sueter gris','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','https://iili.io/H9ERKhX.jpg','Todes','MXN','Sudadera asimétrica con detalle de cierre en pecho.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Sueter all in black' ,'780','Gris','Sueter gris all in black mode','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','https://iili.io/H9ERBBs.jpg','Todes','MXN','Sudadera asimétrica con detalle de cierre en pecho y bordado “All in Black Mood”.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Top Katherine' ,'250','Negro','Top negro con mangas trasparentes','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','https://iili.io/H9ERn4f.jpg','Ellas','MXN','Crop top con mangas transparentes.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Pants Rex' ,'650','Negro','Pants negro','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','https://iili.io/H9ER2pI.jpg','Todes','MXN','Jogger con aplicación en costado, elástico y jareta.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Jogger Rex' ,'650','Negro','Jogger negro','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','https://iili.io/H9EApEJ.jpg','Todes','MXN','Jogger con aplicación en cintura enfrente y atrás, con elástico y jareta.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Air Rosa' ,'250','Rosa','Blusa rosa con espalda en A','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','https://iili.io/H9EAZI1.jpg','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Air Negro' ,'250','Negro','Blusa negra con espalda en A','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','https://iili.io/H9EALmP.jpg','Ellas','MXN','Blusa manga larga con escote en espalda y cintas.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Camisa Autum' ,'650','Negro','Camisa formal','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','https://iili.io/H9EAPdQ.jpg','Todes','MXN','Camisa formal con apicacion en los costados.');
INSERT INTO `productos`(`nombre_prenda`,`precio`,`color`,`descripcion`,`img_principal`,`img0`,`img1`,`img2`,`target`,`divisa`,`detalle`) VALUES ('Camisa Moon' ,'650','Negro','Camisa estilo oriental','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','https://iili.io/H9EA4rx.jpg','Todes','MXN','Camisa negra estilo oriental con detalle en botones.');


INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Patricio','Estrella','patricio@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Bob','Esponja','esponja@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'BobEsp31', 'Cangreburger');
INSERT INTO `cliente` (`nombre`,`apellido`,`correo`,`celular`, `direccion`,`cp`,`usuario`, `contrasena`) VALUES ('Calamardo','Tentaculos','calamardo@email.com','3339556360', 'Gustavo Pena 1341', '45079', 'PathEst31', 'Micajasecreta');
